apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
    helm.sh/chart: {{ include "sabnzbd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sabnzbd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: data
          mountPath: {{ .Values.sabnzbd.dataDir }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.claimName }}
        {{- if .Values.persistence.data.subPath }}
          subPath: {{ .Values.persistence.data.subPath }}
        {{ end }}
        - name: media
          mountPath: {{ .Values.sabnzbd.mediaDir }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.media.claimName }}
        {{- if .Values.persistence.media.subPath }}
          subPath: {{ .Values.persistence.media.subPath }}
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG
              {{- if .Values.sabnzbd.configPath }}
                value: {{ .Values.sabnzbd.configPath }}
              {{- else }}
                value: "{{ .Values.sabnzbd.dataDir }}/config.ini"
              {{- end }}
            - name: SABNZBD_UID
              value: {{ .Values.sabnzbd.uid }}
            - name: SABNZBD_GID
              value: {{ .Values.sabnzbd.uid }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              {{- if .Values.sabnzbd.apiKey }}
                path: "/sabnzbd/api?mode=version&apiley={{ .Values.sabnzbd.apiKey }}"
              {{- else }}
                path: "/sabnzbd/api?mode=version"
              {{- end }}
              port: http
          readinessProbe:
            httpGet:
              {{- if .Values.sabnzbd.apiKey }}
                path: "/sabnzbd/api?mode=version&apiley={{ .Values.sabnzbd.apiKey }}"
              {{- else }}
                path: "/sabnzbd/api?mode=version"
              {{- end }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
